name: zmongol
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.0+20

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  cupertino_icons: ^0.1.3
  mongol: ^2.0.2
  get: ^4.1.4
  flutter_icons: any
  flutter_screenutil: 5.0.0-nullsafety.11
  sqflite: ^2.0.0+3
  flutter_colorpicker:
  path_provider: ^2.0.1
  share: ^2.0.0
  # The owner does not support null-safety for this plugin yet
  # So we use a temporary code from a pull request of a contributor to be able to run project on Flutter 2.x
  # Should check this plugin frequently to update the official plugin version
  image_gallery_saver:
    git:
      url: https://github.com/hui-z/image_gallery_saver.git
      ref: f0f594d315066c91c868a13b8518763d645a0934
  permission_handler: ^7.1.0
  permission_handler_platform_interface: ^3.3.0
  path: ^1.8.0
  image_picker: ^0.7.2
  image_cropper: ^1.4.1
  intl: ^0.17.0
  flutter_slidable: ^0.6.0
  transparent_image: ^2.0.0
  pytorch_mobile:
    git:
      url: https://github.com/leovinsen/pytorch_mobile_clone.git


dev_dependencies:
  flutter_test:
    sdk: flutter
#  pedantic: ^1.10.0-nullsafety.3
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
#    - assets/image/image.jpg
    - assets/machine_learning/zmodel.pt
    - assets/machine_learning/new_char_to_token.json
#    - assets/words52_20200821.db
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: haratig
      fonts:
        - asset: assets/fonts/z52haratig.otf
    - family: z52amglangtig
      fonts:
        - asset: assets/fonts/z52amglangtig.otf
    - family: z52buduntig
      fonts:
        - asset: assets/fonts/z52buduntig.otf
    - family: z52chimegtig
      fonts:
        - asset: assets/fonts/z52chimegtig.otf
    - family: z52egulentig
      fonts:
        - asset: assets/fonts/z52egulentig.otf
    - family: z52hawangtig
      fonts:
        - asset: assets/fonts/z52hawangtig.ttf
    - family: z52holsnujugtig
      fonts:
        - asset: assets/fonts/z52holsnujugtig.otf
    - family: z52horqtsagaantig
      fonts:
        - asset: assets/fonts/z52horqtsagaantig.ttf
    - family: z52munggunujugtig
      fonts:
        - asset: assets/fonts/z52munggunujugtig.ttf
    - family: z52ononsansseriftig
      fonts:
        - asset: assets/fonts/z52ononsansseriftig.ttf
    - family: z52ordostig
      fonts:
        - asset: assets/fonts/z52ordostig.otf
    - family: z52qimedtig
      fonts:
        - asset: assets/fonts/z52qimedtig.otf
    - family: z52qingmingtig
      fonts:
        - asset: assets/fonts/z52qingmingtig.otf
    - family: z52saitig
      fonts:
        - asset: assets/fonts/z52saitig.otf
    - family: z52sanstig
      fonts:
        - asset: assets/fonts/z52sanstig.otf
    - family: z52sanstigbold
      fonts:
        - asset: assets/fonts/z52sanstigbold.otf
    - family: z52solibotig
      fonts:
        - asset: assets/fonts/z52solibotig.otf
    - family: z52sonintig
      fonts:
        - asset: assets/fonts/z52sonintig.otf
    - family: z52togtig
      fonts:
        - asset: assets/fonts/z52togtig.ttf
    - family: z52tsagaantig
      fonts:
        - asset: assets/fonts/z52tsagaantig.otf
    - family: z52uljitig
      fonts:
        - asset: assets/fonts/z52uljitig.ttf

    - family: z52brahmisanstig
      fonts:
        - asset: assets/fonts/z52brahmisanstig.ttf

    - family: Z52HaraTigMirror
      fonts:
        - asset: assets/fonts/z52HaraTigMirror1.ttf
    - family: segoeui
      fonts:
        - asset: assets/fonts/segoeui.ttf
        - asset: assets/fonts/seguisb.ttf
        - asset: assets/fonts/segoeuib.ttf


  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
